# Generated by Django 4.0.1 on 2022-01-28 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_portal', '0003_alter_provider_about_alter_provider_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_portal.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_portal.seeker'),
        ),
        migrations.AlterField(
            model_name='job',
            name='poster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_portal.provider'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_portal.job'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_portal.skill'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seekerskill',
            name='seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_portal.seeker'),
        ),
        migrations.AlterField(
            model_name='seekerskill',
            name='skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_portal.skill'),
        ),
    ]
