# Generated by Django 4.0.1 on 2022-01-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_alter_application_job_alter_application_seeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.seeker'),
        ),
        migrations.AlterField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.provider'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.job'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.skill'),
        ),
        migrations.AlterField(
            model_name='seekerskill',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.seeker'),
        ),
        migrations.AlterField(
            model_name='seekerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.skill'),
        ),
    ]
