# Generated by Django 4.0.1 on 2022-01-31 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_alter_seeker_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_applied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
